source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'AppSets' do
    use_frameworks!
    pod 'Alamofire', '~> 5.9.1'
    pod 'RMQClient', '~> 0.12.0'
    pod 'SwiftEventBus', :tag => '5.1.0', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
    pod 'CryptoSwift', '~> 1.8.2'
    pod 'RealmSwift', '~>10'
    pod 'QCloudCOSXML/Transfer'
  end
