spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181
  application:
    name: OrderServer
  jpa:
    show-sql: true
  datasource:
    custom:
      - id: 0
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://gjzhbdrav2oyp1fwsmgkq89e3uxlc467.mysql.qingcloud.link/db1
        username: root_2
        password: Xcj8575022_
        default: true
      - id: 1
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/information_schema
        username: root
        password: 1234
      - id: 2
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db1
        username: root
        password: 1234
        default: true
server:
  http-port: 8089
  port: 8090
  ssl:
    key-store: classpath:ssl/server.p12
    key-store-password: 1234567890
    key-store-type: PKCS12
    key-alias: 1
logging:
  level:
    xcj.app.a: debug
mybatis:
  mapper-locations: classpath:mappers/*.xml
