spring:
  mvc:
    log-request-details: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/appsets_3?allowMultiQueries=true
    username: root
    password: 1234
  cloud:
    zookeeper:
      connect-string: localhost:2181
  application:
    name: UserServer3
  data:
    mongodb:
#      uri: mongodb://user3:user3pwd@127.0.0.1:27017/authSource=appsets_2023?authMechanism=SCRAM-SHA-1
      host: 127.0.0.1
      port: 27017
      database: appsets_2023
      username: user3
      password: user3pwd
    redis:
      host: 127.0.0.1
      port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: testuser1
    password: testuser1pwd
    virtual-host: /

server:
  port: 8084
  ssl:
    key-store: classpath:ssl/ca.p12
    key-store-password: (AppSets)1224888759
    key-store-type: PKCS12
    key-alias: 1
logging:
  level:
    xcj.* : debug
mybatis:
  mapper-locations: classpath:mappers/*.xml