package xcj.app.compose_share.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import xcj.app.compose_share.foundation_extension.DesignPreview

class DesignPreviewProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        // 1. 找到所有被 @MyTestAnnotation 标记的类
        val symbols = resolver.getSymbolsWithAnnotation(DesignPreview::class.qualifiedName ?: "")
            .filterIsInstance<KSClassDeclaration>()

        symbols.forEach { symbol ->
            // 1. 获取特定的注解对象
            val annotation = symbol.annotations.find {
                it.shortName.asString() == DesignPreview::class.simpleName
            } ?: return@forEach

            // 2. 提取参数

            // 特别注意：KClass 在 KSP 中会被解析为 KSType
            val designHookClass =
                annotation.arguments.find { it.name?.asString() == "designHook" }?.value as KSType

            logger.warn("找到注解: designHookClass=$designHookClass")
        }


        // 2. 生成一个简单的 Kotlin 文件
        val file = codeGenerator.createNewFile(
            Dependencies(false),
            "com.example.generated",
            "GeneratedFunctions"
        )

        file.use { output ->
            output.write("package com.example.generated\n\n".toByteArray())
            output.write("fun helloFromKSP() {\n".toByteArray())
            output.write("    println(\"Hello! This was generated by KSP\")\n".toByteArray())
            output.write("}\n".toByteArray())
        }

        return emptyList() // 返回无法处理的符号
    }
}